import { Product, Category, Collection } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Dresses',
    slug: 'dresses',
    image_url: '/images/product-dress-floral.png',
    description: 'Elegant dresses for every occasion — from casual day dresses to glamorous evening gowns.',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Tops',
    slug: 'tops',
    image_url: '/images/product-top.png',
    description: 'Trendy tops, blouses, and shirts to elevate your everyday style.',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Bottoms',
    slug: 'bottoms',
    image_url: '/images/product-jeans.png',
    description: 'Jeans, skirts, trousers, and more — the perfect foundation for any outfit.',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Shoes',
    slug: 'shoes',
    image_url: '/images/product-heels.png',
    description: 'Step out in style with our curated collection of heels, sneakers, and flats.',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Accessories',
    slug: 'accessories',
    image_url: '/images/product-bag.png',
    description: 'Bags, sunglasses, jewelry, and more — the finishing touches that make the look.',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Sale',
    slug: 'sale',
    image_url: '/images/promo-flash-sale.png',
    description: 'Don\'t miss out! Grab these stunning pieces at unbeatable prices.',
    created_at: new Date().toISOString(),
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Floral Midi Dress',
    slug: 'floral-midi-dress',
    description: 'A beautiful floral midi dress with a flattering silhouette. Perfect for brunches, garden parties, and sunny afternoons. The soft violet and pink floral pattern adds a romantic touch, while the flowing fabric ensures all-day comfort.',
    price: 15000,
    original_price: null,
    category_id: '1',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Violet Floral', 'Blue Floral', 'Pink Floral'],
    images: ['/images/product-dress-floral.png'],
    is_new_arrival: true,
    is_best_seller: true,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Classic Black Blazer',
    slug: 'classic-black-blazer',
    description: 'A timeless fitted black blazer with elegant gold button details. This versatile piece transitions effortlessly from boardroom meetings to evening dinners. Tailored for a flattering fit with structured shoulders.',
    price: 22000,
    original_price: 28000,
    category_id: '2',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Charcoal'],
    images: ['/images/product-blazer.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Nude Leather Crossbody',
    slug: 'nude-leather-crossbody',
    description: 'An elegant structured crossbody bag in soft nude leather with gold hardware. The perfect everyday companion with multiple compartments for organization. Adjustable strap for crossbody or shoulder wear.',
    price: 18500,
    original_price: null,
    category_id: '5',
    sizes: ['One Size'],
    colors: ['Nude', 'Black', 'Tan'],
    images: ['/images/product-bag.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Blush Pink Stilettos',
    slug: 'blush-pink-stilettos',
    description: 'Stunning dusty rose stiletto heels with a pointed toe design. These elegant heels add sophistication to any outfit, from office attire to evening wear. Comfortable padded insole for extended wear.',
    price: 16000,
    original_price: 20000,
    category_id: '4',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['Blush Pink', 'Black', 'Nude'],
    images: ['/images/product-heels.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Lavender Ribbed Crop Top',
    slug: 'lavender-ribbed-crop-top',
    description: 'A trendy ribbed knit crop top in a gorgeous lavender shade. This casual chic piece pairs beautifully with high-waisted jeans or skirts. Soft, stretchy fabric for a comfortable fit.',
    price: 6500,
    original_price: null,
    category_id: '2',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Lavender', 'White', 'Black', 'Sage'],
    images: ['/images/product-top.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Wide-Leg Denim Jeans',
    slug: 'wide-leg-denim-jeans',
    description: 'Modern high-waisted wide-leg jeans in a rich dark indigo wash. These trendy jeans offer a relaxed, flattering silhouette with a comfortable stretch denim fabric. A wardrobe essential.',
    price: 12000,
    original_price: null,
    category_id: '3',
    sizes: ['24', '26', '28', '30', '32'],
    colors: ['Dark Indigo', 'Light Wash', 'Black'],
    images: ['/images/product-jeans.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Emerald Satin Slip Dress',
    slug: 'emerald-satin-slip-dress',
    description: 'An exquisite emerald green satin slip dress with delicate spaghetti straps. This luxurious midi dress drapes beautifully and is perfect for date nights, cocktail parties, or any special occasion.',
    price: 19500,
    original_price: 25000,
    category_id: '1',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Emerald', 'Burgundy', 'Black', 'Champagne'],
    images: ['/images/product-dress-satin.png'],
    is_new_arrival: true,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'White Platform Sneakers',
    slug: 'white-platform-sneakers',
    description: 'Trendy all-white platform sneakers for a casual-cool look. The chunky sole adds height and edge, while the classic white colorway matches everything in your wardrobe.',
    price: 14000,
    original_price: null,
    category_id: '4',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['White', 'White/Pink', 'White/Black'],
    images: ['/images/product-sneakers.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Champagne Pleated Skirt',
    slug: 'champagne-pleated-skirt',
    description: 'An elegant satin pleated midi skirt in a stunning champagne gold. The flowing pleats create beautiful movement with every step. Pairs perfectly with a tucked-in blouse or fitted top.',
    price: 11000,
    original_price: 14000,
    category_id: '3',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Champagne', 'Silver', 'Black', 'Blush'],
    images: ['/images/product-skirt.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Cat-Eye Tortoiseshell Sunglasses',
    slug: 'cat-eye-tortoiseshell-sunglasses',
    description: 'Stylish oversized cat-eye sunglasses in classic tortoiseshell. These statement sunglasses add instant glamour to any look. UV400 protection lenses for both style and sun safety.',
    price: 8500,
    original_price: null,
    category_id: '5',
    sizes: ['One Size'],
    colors: ['Tortoiseshell', 'Black', 'Clear'],
    images: ['/images/product-sunglasses.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
];

export const collections: Collection[] = [
  {
    id: '1',
    name: 'Date Night',
    slug: 'date-night',
    description: 'Looks that turn heads. Dress to impress for your next evening out.',
    image_url: '/images/collection-datenight.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Office Chic',
    slug: 'office-chic',
    description: 'Power dressing meets modern elegance. Own the boardroom.',
    image_url: '/images/collection-office.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Weekend Vibes',
    slug: 'weekend-vibes',
    description: 'Relaxed styles for the perfect weekend. Comfort meets fashion.',
    image_url: '/images/collection-weekend.png',
    created_at: new Date().toISOString(),
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency',
    currency: 'KES',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getDiscountPercentage(price: number, originalPrice: number): number {
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}
