import { Product, Category, Collection } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Women',
    slug: 'women',
    image_url: '/images/product-dress-floral.png',
    description: 'Curated fashion for the modern Kenyan woman — from elegant ankara to casual everyday wear.',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Men',
    slug: 'men',
    image_url: '/images/product-blazer.png',
    description: 'Sharp, stylish menswear — from smart casual to statement pieces.',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Kids',
    slug: 'kids',
    image_url: '/images/product-top.png',
    description: 'Adorable and durable fashion for the little ones.',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Accessories',
    slug: 'accessories',
    image_url: '/images/product-bag.png',
    description: 'Bags, shoes, sunglasses and more — the finishing touches that make the look.',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Home',
    slug: 'home',
    image_url: '/images/collection-weekend.png',
    description: 'Statement carpets, doormats, and home décor — dress your space with warmth.',
    created_at: new Date().toISOString(),
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Ankara Print Midi Dress',
    slug: 'ankara-print-midi-dress',
    description: 'A stunning ankara print midi dress with a flattering silhouette. Perfect for brunches, garden parties, and sunny Nairobi afternoons. The vibrant pattern adds a bold touch, while the flowing fabric ensures all-day comfort.',
    price: 3500,
    original_price: null,
    category_id: '1',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Violet Floral', 'Blue Floral', 'Pink Floral'],
    images: ['/images/product-dress-floral.png'],
    is_new_arrival: true,
    is_best_seller: true,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Classic Oxford Shirt',
    slug: 'classic-oxford-shirt',
    description: 'A timeless fitted oxford shirt with elegant details. This versatile piece transitions effortlessly from boardroom meetings to evening dinners. Tailored for a flattering fit with premium cotton fabric.',
    price: 2800,
    original_price: 4500,
    category_id: '2',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Light Blue', 'Pink'],
    images: ['/images/product-blazer.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Leather Crossbody Bag',
    slug: 'leather-crossbody-bag',
    description: 'An elegant structured crossbody bag in soft leather with gold hardware. The perfect everyday companion with multiple compartments. Adjustable strap for crossbody or shoulder wear.',
    price: 4500,
    original_price: null,
    category_id: '4',
    sizes: ['One Size'],
    colors: ['Tan', 'Black', 'Nude'],
    images: ['/images/product-bag.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Statement Stilettos',
    slug: 'statement-stilettos',
    description: 'Stunning stiletto heels with a pointed toe design. These elegant heels add sophistication to any outfit, from office attire to evening wear. Comfortable padded insole for extended wear.',
    price: 3200,
    original_price: 5000,
    category_id: '4',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['Blush Pink', 'Black', 'Nude'],
    images: ['/images/product-heels.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Ribbed Crop Top',
    slug: 'ribbed-crop-top',
    description: 'A trendy ribbed knit crop top in gorgeous shades. This casual chic piece pairs beautifully with high-waisted jeans or skirts. Soft, stretchy fabric for a comfortable fit.',
    price: 1200,
    original_price: null,
    category_id: '1',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['White', 'Black', 'Sage', 'Lavender'],
    images: ['/images/product-top.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Wide-Leg Denim Jeans',
    slug: 'wide-leg-denim-jeans',
    description: 'Modern high-waisted wide-leg jeans in a rich dark indigo wash. These trendy jeans offer a relaxed, flattering silhouette with a comfortable stretch denim fabric.',
    price: 2800,
    original_price: null,
    category_id: '1',
    sizes: ['24', '26', '28', '30', '32'],
    colors: ['Dark Indigo', 'Light Wash', 'Black'],
    images: ['/images/product-jeans.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Emerald Satin Dress',
    slug: 'emerald-satin-dress',
    description: 'An exquisite emerald green satin dress with delicate details. This luxurious piece drapes beautifully and is perfect for date nights, cocktail parties, or any special occasion.',
    price: 4200,
    original_price: 6500,
    category_id: '1',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Emerald', 'Burgundy', 'Black', 'Champagne'],
    images: ['/images/product-dress-satin.png'],
    is_new_arrival: true,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'White Platform Sneakers',
    slug: 'white-platform-sneakers',
    description: 'Trendy all-white platform sneakers for a casual-cool look. The chunky sole adds height and edge, while the classic white colorway matches everything in your wardrobe.',
    price: 3500,
    original_price: null,
    category_id: '4',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['White', 'White/Pink', 'White/Black'],
    images: ['/images/product-sneakers.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Shuka Print Doormat',
    slug: 'shuka-print-doormat',
    description: 'A vibrant Maasai-inspired shuka print doormat. Durable, easy to clean, and adds an instant pop of Kenyan warmth to your entryway.',
    price: 1500,
    original_price: 2000,
    category_id: '5',
    sizes: ['Standard', 'Large'],
    colors: ['Red/Blue', 'Green/Red', 'Multi'],
    images: ['/images/product-skirt.png'],
    is_new_arrival: false,
    is_best_seller: true,
    is_on_sale: true,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Cat-Eye Sunglasses',
    slug: 'cat-eye-sunglasses',
    description: 'Stylish oversized cat-eye sunglasses in classic tortoiseshell. UV400 protection lenses for both style and sun safety.',
    price: 1800,
    original_price: null,
    category_id: '4',
    sizes: ['One Size'],
    colors: ['Tortoiseshell', 'Black', 'Clear'],
    images: ['/images/product-sunglasses.png'],
    is_new_arrival: true,
    is_best_seller: false,
    is_on_sale: false,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
];

export const collections: Collection[] = [
  {
    id: '1',
    name: 'The Soko Edit',
    slug: 'soko-edit',
    description: 'Our curated marketplace collection — the best of Kenyan style and home living.',
    image_url: '/images/collection-datenight.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Home Essentials',
    slug: 'home-essentials',
    description: 'Statement carpets, doormats, and décor that dress your space with warmth.',
    image_url: '/images/collection-office.png',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Weekend Vibes',
    slug: 'weekend-vibes',
    description: 'Relaxed styles for the perfect Kenyan weekend. Comfort meets fashion.',
    image_url: '/images/collection-weekend.png',
    created_at: new Date().toISOString(),
  },
];

export function formatPrice(price: number): string {
  return `KSh ${new Intl.NumberFormat('en-KE', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)}`;
}

export function getDiscountPercentage(price: number, originalPrice: number): number {
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}
